StLouisSites2/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites2.Models
{
    public class Location
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string County { get; set; }

        public List<LocationRating> LocationRatings { get; set; }

    }
}

StLouisSites2/ViewModels/Location/LocationCreateViewModel.cs
using StLouisSites2.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites2.ViewModels.Location
{
    public class LocationCreateViewModel
    {
        private ApplicationDbContext context;

        //public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required(ErrorMessage = "Description must be between 3 and 200 characters.")]
        [MinLength(3)]
        [MaxLength(200)]
        public string Description { get; set; }
        public string Address { get; set; }
        [Required]
        public string County { get; set; }

        [Display(Name = "Select One or More Categories")]
        public List<int> CategoryIDs { get; set; }
        public List<Models.Category> Categories { get; set; }

        public LocationCreateViewModel() { }

        //gets the category objects (put into a list) from context so we can use them in the view model
        public LocationCreateViewModel(ApplicationDbContext context)
        {
            this.Categories = context.Categories.ToList();
        }

        //this persists the location
        public void CreateLocation(ApplicationDbContext context, LocationCreateViewModel locationViewModel)
        {
            Models.Location location = new Models.Location();
            {
                location.Name = locationViewModel.Name;
                location.Description = locationViewModel.Description;
                location.Address = locationViewModel.Address;
                location.County = locationViewModel.County;
            }
            //have to specify becaue there are multiple lists in DbContext
            context.Locations.Add(location);
            List<Models.CategoryLocation> categoryLocations = CreateCategoryLocationRelationships(location.ID);
            //this refers to the list stored in the Location model
            location.CategoryLocations = categoryLocations;
            context.SaveChanges();

            
        }
        //where does this locationID some from?
        //where does categoryId come from?
        //I think it's supposed to come from the CategoryLocation model, but we are setting it here, correct?
        //so shouldn't it be an is that gets passed in somehow? maybe that's location ID
        //but where does categoryID come from? wouldn't that be the same ID?
        private List<Models.CategoryLocation> CreateCategoryLocationRelationships(int locationID)
        {
            return CategoryIDs.Select(categoryID => new Models.CategoryLocation { LocationID = locationID, CategoryID = categoryID }).ToList();
        }



            
            
            
        }

    
    }

StLouisSites2/ViewModels/Location/LocationDetailsViewModel.cs
using Microsoft.EntityFrameworkCore;
using StLouisSites2.Data;
using StLouisSites2.ViewModels.LocationRating;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites2.ViewModels.Location
{
    public class LocationDetailsViewModel
    {
        private ApplicationDbContext context;
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<LocationRatingDetailsViewModel> LocationRatingDetailsViewModels { get; set; }
        public List<Models.LocationRating> Reviews { get; set; }
        public string CategoryNames { get; set; }
        public List<Models.CategoryLocation> CategoryLocations { get; set; }


        public static LocationDetailsViewModel GetLocationDetailsViewModel(ApplicationDbContext context, int id)
        {
            //make an instance of a view model //we are not assigning the id, we are finding the LocationRating that has the same LocationId
            //as the ID of the Location object that we (passed in) and then assign it properties
            //we are not assigning the id, we are finding the LocationRating that has the same LocationId
            //as the ID of the Location object that we passed in

            Models.Location location = context.Locations
                .Include(l => l.CategoryLocations)
                    .ThenInclude(cl => cl.Category)
                .Single(l => l.ID == id);
                


            //include or 2 selects or 2 wheres do not work
            //location = context.Locations.Select(l => l.Name);
            //location = context.Locations.Select(l => l.Description)


            //then, assign allofthe properties of the viewmodel to the location object??

            //COMMENTTED OUT!!!! - put in constructor in the bottom
            //locationDetailsViewModel.Name = location.Name;
            //locationDetailsViewModel.Description = location.Description;
            //locationDetailsViewModel.ID = location.ID;

            //then, to get the list of ratings and reviews that I need to display on the Details view
            //I have to create an instance of a LocationRating object
            //then, I have to check that/get the viewmodel id that was passed in from location index
            //matches the locationID in the Location Rating class and connect them.
            //find it through query
            // Models.LocationRating locationRating = context.LocationRatings
            //.Single(r => r.LocationID == locationDetailsViewModel.ID);


            //so I have made an instance of this, and because this is a foreign id, I can get all of the
            //properties associated with this specific Location Rating object

            List<Models.LocationRating> locationRatings = context.LocationRatings
                .Where(r => r.LocationID == id)
                .ToList();
            List<LocationRatingDetailsViewModel> locationRatingDetailsViewModels = new List<LocationRatingDetailsViewModel>();
            foreach (Models.LocationRating locationRating in locationRatings)
            {
                LocationRatingDetailsViewModel locationRatingDetailsViewModel = new LocationRatingDetailsViewModel();
                locationRatingDetailsViewModel.Rating = locationRating.Rating;
                locationRatingDetailsViewModel.Review = locationRating.Review;
                locationRatingDetailsViewModels.Add(locationRatingDetailsViewModel);

            }


            LocationDetailsViewModel locationDetailsViewModel = new LocationDetailsViewModel();
            locationDetailsViewModel.LocationRatingDetailsViewModels = locationRatingDetailsViewModels;
            locationDetailsViewModel.Name = location.Name;
            locationDetailsViewModel.Description = location.Description;
            locationDetailsViewModel.ID = location.ID;
            locationDetailsViewModel.CategoryLocations = location.CategoryLocations;
            locationDetailsViewModel.CategoryNames = locationDetailsViewModel.GetCategoryNames(location);

            
            locationDetailsViewModel.LocationRatingDetailsViewModels = locationRatingDetailsViewModels;
            return locationDetailsViewModel;
        }

        

        private string GetCategoryNames(Models.Location location)
        {
           
            return string.Join(",", location.CategoryLocations
                //.Where(cl => cl.CategoryID == cl.Category.ID)
                .Select(cl => cl.Category.Name)
                .Distinct());
            
        }



        //List<Models.LocationRating> locationRatings = new List<Models.LocationRating>();


        //we need to find all of the Rating that are associated with the Location that had that ID and make
        //them into a list
        //we also need to find all of the Review that are associated with the Location that had that ID and make
        //them into a list
        //so, we can just display these two lists in the view model
        //can we do that?
        //I made lists of Ratings and Reviews as properties in the view model
        //then, I need to change these Location and Location Rating objects to ViewModel objects
        //so that they can be used in the view?


    }
    //public static List<LocationDetailsViewModel>GetLocationDetailsViewModel(ApplicationDbContext context)
    //{
    //    List<Models.Location> locations = context.Locations
    //        .Include(l => l.LocationRatings)
    //        .ToList();
    //    List<LocationDetailsViewModel> viewModelLocations = new List<LocationDetailsViewModel>();
    //    foreach (Models.Location location in locations)
    //    {
    //        LocationDetailsViewModel viewModel = new LocationDetailsViewModel();
    //        viewModel.ID = location.ID;
    //        viewModel.Name = location.Name;
    //        viewModel.Description = location.Description;
    //        viewModel.LocationRatings = location.LocationRatings;
    //        viewModel.Reviews = location.LocationRatings.Select(r => r.Review).ToList();
    //    }
}    
    

StLouisSites2/ViewModels/Location/LocationEditViewModel.cs
using Microsoft.EntityFrameworkCore;
using StLouisSites2.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites2.ViewModels.Location
{
    public class LocationEditViewModel
    {
        private ApplicationDbContext context;
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required(ErrorMessage = "Description must be between 3 and 200 characters.")]
        [MinLength(3)]
        [MaxLength(200)]
        public string Description { get; set; }
        public string Address { get; set; }
        [Required]
        public string County { get; set; }
        public List<int>CategoryIDs { get; set; }
        public List<Models.Category>Categories { get; set; }

        public LocationEditViewModel() { }

        public LocationEditViewModel (int id, ApplicationDbContext context)
        {
            //gets the location object from context by id
            Models.Location location = context.Locations
                .Include(l => l.CategoryLocations)
                .Single(l => l.ID == id);
           
            //returns a populated LocationEditViewModel object
            

            Name = location.Name;
            Description = location.Description;
            Address = location.Address;
            County = location.County;
            CategoryIDs = location.CategoryLocations.Select(cl => cl.CategoryID).ToList();
            Categories = context.Categories.ToList();
        }
            
        //creates an instance of populated Location object and updates database with changes
        public void Persist(int id, ApplicationDbContext context)
        {
            Models.Location location = new Models.Location()
            {
                ID = id,
                Name = this.Name,
                Description = this.Description,
                Address = this.Address,
                County = this.County
            };
            context.Update(location);
            List<Models.CategoryLocation> categoryLocations = CreateCategoryLocationRelationships(location.ID);
            location.CategoryLocations = categoryLocations;
            context.SaveChanges();

        }
        private List<Models.CategoryLocation> CreateCategoryLocationRelationships (int locationID)
        {
            return CategoryIDs.Select(catID => new Models.CategoryLocation { LocationID = locationID, CategoryID = catID })
                .ToList();
        }
        
    }
}

StLouisSites2/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StLouisSites2.Data;
using StLouisSites2.Models;
using StLouisSites2.ViewModels.Location;
using StLouisSites2.ViewModels.LocationRating;

namespace StLouisSites2.Controllers
{
    public class LocationController : Controller
    {
        private ApplicationDbContext context;

        public LocationController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            List<LocationListViewModel> viewModelLocations = LocationListViewModel.GetLocationListViewModel(context);
            return View(viewModelLocations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            LocationCreateViewModel locationViewModel = new LocationCreateViewModel(context);
            return View(locationViewModel);
        }
        [HttpPost]
        public IActionResult Create(LocationCreateViewModel locationViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(locationViewModel);
            }

            locationViewModel.CreateLocation(context, locationViewModel);
            
            return RedirectToAction(nameof(Index));
            
        }

        public IActionResult Details(int id)
        {
           
            LocationDetailsViewModel locationDetailsViewModel = LocationDetailsViewModel.GetLocationDetailsViewModel(context, id);
            return View(locationDetailsViewModel);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            return View(model:new LocationEditViewModel(id, context));
        }

        [HttpPost]
        public IActionResult Edit(LocationEditViewModel locationEditViewModel, int id)
        {
            if (!ModelState.IsValid)
            {
                return View(new LocationEditViewModel());
            }
            locationEditViewModel.Persist(id, context);
            return RedirectToAction(actionName: nameof(Index));
        }
    }
}

StLouisSites2/Controllers/LocationRatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StLouisSites2.Data;
using StLouisSites2.Models;
using StLouisSites2.ViewModels.LocationRating;

namespace StLouisSites2.Controllers
{
    public class LocationRatingController : Controller
    {
        private ApplicationDbContext context;

        public LocationRatingController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create(int locationID)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(LocationRatingCreateViewModel locationRatingCreateViewModel)
        {
            int ID = LocationRatingCreateViewModel.GetLocationRatingViewModel(context, locationRatingCreateViewModel);
           
            return RedirectToAction(controllerName: nameof(Location), actionName: nameof(Index));
        }
    }
}

StLouisSites2/Views/Location/Create.cshtml
@model StLouisSites2.ViewModels.Location.LocationCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label">County</label>
                <select asp-for="County">
                    <option>St Louis City</option>
                    <option>St Louis County</option>
                    <option>St. Charles</option>
                </select>
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryIDs" class="control-label"></label>
                @foreach (var category in Model.Categories)
                {
                    <label>@category.Name</label>
                    <input type="checkbox" name="CategoryIDs" value="@category.ID" />
                }
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSites2/Views/Location/Details.cshtml
@model StLouisSites2.ViewModels.Location.LocationDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<p>
    <a asp-controller="LocationRating" asp-action="Create" asp-route-locationID="@Model.ID">Rate/Review</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Category(ies)
            </th>
            <th>
                Ratings
            </th>
            <th>
                Reviews
            </th>

        </tr>
    </thead>
    <tbody>
        
        <tr>

            <td>
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.CategoryNames)
            </td>

            @foreach (var item in Model.LocationRatingDetailsViewModels)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
            }
            @foreach (var item in Model.LocationRatingDetailsViewModels)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Review)
                </td>
            }

            @*@foreach (var item in Model.LocationRatingDetailsViewModels)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
        }*@
        </tr>
    @*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@



            
</tbody>
</table>

StLouisSites2/Views/Location/Edit.cshtml
@model StLouisSites2.ViewModels.Location.LocationEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Edit a Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="ID" class="control-label"></label>*@
                <input hidden asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" value="@Model.Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" value ="@Model.Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" value ="@Model.Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <select asp-for="County">
                    <option>St Louis City</option>
                    <option>St Louis County</option>
                    <option>St. Charles</option>
                </select>
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryIDs" class="control-label"></</label>
                @foreach (var category in Model.Categories)
                {
                    <label>@category.Name</label>
                    @if (Model.CategoryIDs.Contains(category.ID))
                    {
                        <input type="checkbox" value="@category.ID" name="CategoryIDs" checked />
                    }
                    else
                    {
                        <input type="checkbox" value="@category.ID" name="CategoryIDs"  />
                    }
                }
            </div>
            <div class="form-group">
                <button type="submit" value="Save" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSites2/Views/Location/Index.cshtml
@model IEnumerable<StLouisSites2.ViewModels.Location.LocationListViewModel>

@{
    ViewData["Title"] = "Locations";
}

<h1>Locations</h1>

<p>
    <a asp-action="Create">Add a new location</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Location
                @*@Html.DisplayNameFor(model => model.Name)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Average Rating
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td><a asp-controller="Location" asp-action="Details" asp-route-ID="@item.ID">@item.Name</a>
                @*@Html.DisplayFor(modelItem => item.Name)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AverageRating)
            </td>
            <td>
            <td><a asp-controller="LocationRating" asp-action="Create" asp-route-locationID="@item.ID">Rate/Review</a></td>
            <td>
                |
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
}
    </tbody>
</table>